# Generated by Django 3.2.3 on 2021-06-02 22:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('mcc_code', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('workplace', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('registration_date', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('income', models.FloatField()),
                ('expenses', models.FloatField()),
                ('deposit', models.BooleanField()),
                ('credit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('read_status', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.category')),
                ('clients', models.ManyToManyField(to='analytics.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_company', models.CharField(max_length=100)),
                ('subtype', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('transaction_type', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.client')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.category')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_company', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(null=True)),
                ('amount', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.client')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.category')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('f_score', models.FloatField(default=0)),
                ('data', models.ManyToManyField(to='analytics.RecommendationData')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('category', models.CharField(choices=[('Каршеринг', 'Каршеринг'), ('Супермаркеты', 'Супермаркеты'), ('Такси', 'Такси'), ('Музыка', 'Музыка'), ('Фастфуд', 'Фастфуд'), ('Транспорт', 'Транспорт'), ('Аптеки', 'Аптеки'), ('Кино', 'Кино'), ('Книги', 'Книги'), ('Развелечения', 'Развлечения'), ('Красота', 'Красота'), ('Образование', 'Образование'), ('Одежда и обувь', 'Одежда и обувь'), ('Рестораны', 'Рестораны'), ('Топливо', 'Топливо'), ('Животные', 'Животные'), ('Дом и ремонт', 'Дом и ремонт'), ('Спорттовары', 'Спорттовары'), ('Сувениры', 'Сувениры'), ('Фото и видео', 'Фото и видео'), ('Цветы', 'Цветы'), ('Аренда авто', 'Аренда авто'), ('Автоуслуги', 'Автоуслуги'), ('Авиабилеты', 'Авиабилеты'), ('Дьюти-фри', 'Дьюти-фри'), ('Железнодорожные билеты', 'Железнодорожные билеты'), ('Искусство', 'Искусство'), ('Переводы', 'Переводы'), ('Другое', 'Другое')], max_length=50)),
                ('clients_number', models.IntegerField(default=0)),
                ('date_start', models.DateField(default=datetime.date.today)),
                ('date_end', models.DateField(default=datetime.date.today)),
                ('days', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('confirmation_status', models.BooleanField(default=False)),
                ('completion_status', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('acceptance_status', models.BooleanField(default=False)),
                ('acceptance_date', models.DateTimeField(blank=True, null=True)),
                ('forecast_conversion_rate', models.FloatField(default=0)),
                ('forecast_click_through_rate', models.FloatField(default=0)),
                ('forecast_cost_per_action', models.FloatField(default=0)),
                ('forecast_cost_per_click', models.FloatField(default=0)),
                ('clients', models.ManyToManyField(to='analytics.Client')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_number', models.IntegerField(default=0)),
                ('clicked_number', models.IntegerField(default=0)),
                ('performed_action_number', models.IntegerField(default=0)),
                ('clicked_clients', models.ManyToManyField(related_name='commercial_clicked_clients', to='analytics.Client')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_info', to='analytics.order')),
                ('performed_action_clients', models.ManyToManyField(related_name='commercial_performed_action_clients', to='analytics.Client')),
                ('shown_clients', models.ManyToManyField(related_name='commercial_shown_clients', to='analytics.Client')),
            ],
        ),
    ]
