# Generated by Django 3.2.3 on 2021-05-14 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('mcc_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('workplace', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('registration_date', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('income', models.FloatField()),
                ('expenses', models.FloatField()),
                ('deposit', models.BooleanField()),
                ('credit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=100)),
                ('category', models.CharField(choices=[('Каршеринг', 'Каршеринг'), ('Супермаркеты', 'Супермаркеты'), ('Такси', 'Такси'), ('Музыка', 'Музыка'), ('Фастфуд', 'Фастфуд'), ('Транспорт', 'Транспорт'), ('Аптеки', 'Аптеки'), ('Кино', 'Кино'), ('Книги', 'Книги'), ('Развелечения', 'Развлечения'), ('Красота', 'Красота'), ('Образование', 'Образование'), ('Одежда и обувь', 'Одежда и обувь'), ('Рестораны', 'Рестораны'), ('Топливо', 'Топливо'), ('Животные', 'Животные'), ('Дом и ремонт', 'Дом и ремонт'), ('Спорттовары', 'Спорттовары'), ('Сувениры', 'Сувениры'), ('Фото и видео', 'Фото и видео'), ('Цветы', 'Цветы'), ('Аренда авто', 'Аренда авто'), ('Автоуслуги', 'Автоуслуги'), ('Авиабилеты', 'Авиабилеты'), ('Дьюти-фри', 'Дьюти-фри'), ('Железнодорожные билеты', 'Железнодорожные билеты'), ('Искусство', 'Искусство'), ('Переводы', 'Переводы'), ('Другое', 'Другое')], max_length=50)),
                ('transactions_number', models.IntegerField(default=0)),
                ('clients_number', models.IntegerField(default=0)),
                ('date_start', models.DateField(default=datetime.date.today)),
                ('date_end', models.DateField(default=datetime.date.today)),
                ('days', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('product_category', models.IntegerField()),
                ('product_company', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(null=True)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('product_company', models.CharField(max_length=100)),
                ('product_category', models.IntegerField()),
                ('subtype', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('transaction_type', models.CharField(max_length=20)),
            ],
        ),
    ]
