# Generated by Django 3.2.3 on 2021-05-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=12, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
