# Generated by Django 3.2.3 on 2021-06-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20210603_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationdata',
            name='clients',
            field=models.ManyToManyField(blank=True, to='analytics.Client'),
        ),
    ]
