# Generated by Django 3.2.3 on 2021-05-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='mcc_code',
            field=models.CharField(max_length=300),
        ),
    ]
