# Generated by Django 3.2.3 on 2021-05-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clients',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
