# Generated by Django 3.2.3 on 2021-05-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_order_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='confirmation_status',
        ),
        migrations.AddField(
            model_name='order',
            name='completion_status',
            field=models.BooleanField(default=False),
        ),
    ]
