# Generated by Django 3.2.3 on 2021-05-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20210519_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completion_time',
            new_name='completion_date',
        ),
    ]
