# Generated by Django 3.2.3 on 2021-05-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_rename_completion_time_order_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='acceptance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='acceptance_status',
            field=models.BooleanField(default=False),
        ),
    ]
