# Generated by Django 3.2.3 on 2021-05-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_auto_20210520_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('read_status', models.BooleanField(default=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
