# Generated by Django 3.2.3 on 2021-05-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
