# Generated by Django 3.2.3 on 2021-05-27 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_remove_order_transactions_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_number', models.IntegerField(default=0)),
                ('clicked_number', models.IntegerField(default=0)),
                ('clients', models.JSONField(blank=True, null=True)),
                ('target_actions', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.order')),
            ],
        ),
    ]
