# Generated by Django 3.2.3 on 2021-05-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_commercialinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialinfo',
            old_name='target_actions',
            new_name='performed_action_number',
        ),
        migrations.RenameField(
            model_name='commercialinfo',
            old_name='clients',
            new_name='shown_clients',
        ),
        migrations.AddField(
            model_name='commercialinfo',
            name='clicked_clients',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialinfo',
            name='performed_action_clients',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
