# Generated by Django 3.2.3 on 2021-05-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_alter_order_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.JSONField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.category')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('data', models.ManyToManyField(to='analytics.RecommendationData')),
            ],
        ),
    ]
