# Generated by Django 3.2.3 on 2021-05-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_recommendationdata_recommendationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationmodel',
            name='data',
            field=models.ManyToManyField(null=True, to='analytics.RecommendationData'),
        ),
    ]
