# Generated by Django 3.2.3 on 2021-05-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0021_alter_recommendationmodel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationmodel',
            name='data',
            field=models.ManyToManyField(blank=True, null=True, to='analytics.RecommendationData'),
        ),
    ]

