# Generated by Django 3.2.3 on 2021-05-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0022_alter_recommendationmodel_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationmodel',
            name='f_score',
            field=models.FloatField(default=0),
        ),
    ]
