# Generated by Django 3.2.3 on 2021-05-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0023_recommendationmodel_f_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='forecast_click_through_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='forecast_conversion_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='forecast_cost_per_action',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='forecast_cost_per_click',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Каршеринг', 'Каршеринг'), ('Супермаркеты', 'Супермаркеты'), ('Такси', 'Такси'), ('Музыка', 'Музыка'), ('Фастфуд', 'Фастфуд'), ('Транспорт', 'Транспорт'), ('Аптеки', 'Аптеки'), ('Кино', 'Кино'), ('Книги', 'Книги'), ('Развелечения', 'Развлечения'), ('Красота', 'Красота'), ('Образование', 'Образование'), ('Одежда и обувь', 'Одежда и обувь'), ('Рестораны', 'Рестораны'), ('Топливо', 'Топливо'), ('Животные', 'Животные'), ('Дом и ремонт', 'Дом и ремонт'), ('Спорттовары', 'Спорттовары'), ('Сувениры', 'Сувениры'), ('Фото и видео', 'Фото и видео'), ('Цветы', 'Цветы'), ('Аренда авто', 'Аренда авто'), ('Автоуслуги', 'Автоуслуги'), ('Авиабилеты', 'Авиабилеты'), ('Дьюти-фри', 'Дьюти-фри'), ('Железнодорожные билеты', 'Железнодорожные билеты'), ('Искусство', 'Искусство'), ('Переводы', 'Переводы'), ('Другое', 'Другое')], max_length=50),
        ),
    ]
